version: '3.8'

services:
  # Serviço do Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: books_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bd:/docker-entrypoint-initdb.d 
    networks:
      - webnet

  # Serviço do PHPMyAdmin para gerenciar o banco de dados
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - webnet

  # Serviço do Backend 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_HOST: mysql-db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: books_db
      PORTA: 4444
      ESCREVER_LOG_ARQUIVO: "true"
      DATABASE_URL: "mysql://root:password@mysql-db:3306/books_db"
    ports:
      - "4444:4444"
    volumes:
      - backend_logs:/app/log 
    depends_on:
      - mysql
    networks:
      - webnet

  # Serviço do Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      VITE_API_BASE_URL: http://localhost:4444
      VITE_ROTA_INFOS_API: http://localhost:4444/api/home
      VITE_ROTA_LIVROS: http://localhost:4444/api/livros 
    ports:
      - "3000:80"
    networks:
      - webnet

networks:
  webnet:

volumes:
  mysql_data:
  backend_logs:
