version: '3'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - cord_cont_network

  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "4000:4000"
    networks:
      - cord_cont_network

networks:
  cord_cont_network:
    driver: bridge
