version: '3'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8000:80"  
    depends_on:
      - back
    networks:
      - cord_cont_network

  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "4444:4444"  
    networks:
      - cord_cont_network

networks:
  cord_cont_network:
    driver: bridge
